### ISSUE TITLE
Implement `express-session`

### ISSUE THREAD

**Issue by ecumene** [swatigetcoding0610/blue_bee#11]
- [x] [Follow this tutorial ](https://www.npmjs.com/package/express-session)
- [x] Create a schema (table) for the Users * KEEP THE PRODUCTS TABLE!

User table properties
```
id -> integer primary key,
email -> text not null,
password -> text not null,
create_at -> datetime default now() // Not the right syntax!
```

**Comment by sverma06** [comment]
created table for user sign up 
`CREATE TABLE IF NOT EXISTS user (
        user_id INTEGER PRIMARY KEY,
        email TEXT NOT NULL,
        password TEXT DEFAULT 0,
        create_at INTEGER DEFAULT 0
    )`

**Comment by ecumene** [comment]
Try following this too: https://github.com/IsabelMcIlroy/KnitAndPearl/pull/22/files

**Comment by ecumene** [comment]
Visit "User Login" on this page: https://www.npmjs.com/package/express-session

**Comment by ecumene** [comment]
![Image](https://user-images.githubusercontent.com/6249465/198844681-c0aa4d24-1d00-44e8-b320-0fee3192de2a.png)
