### ISSUE TITLE
Create user table

### ISSUE THREAD

**Issue by ecumene** [swatigetcoding0610/blue_bee#12]

**Comment by sverma06** [comment]
Created a table with the name `userLoginInfo`

`CREATE TABLE IF NOT EXISTS userLoginInfo (
        user_id INTEGER PRIMARY KEY,
        password TEXT DEFAULT 0,
    )`

**Comment by ecumene** [comment]
`userLoginInfo` could just be `users` and the password should be `NOT NULL` so you can remove the `DEFAULT`. Having a default implies that the password can be null (which you reeeeeeally don't want :) )

```
CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER PRIMARY KEY,
  password TEXT NOT NULL
)
```
