### ISSUE TITLE
Create product table

### ISSUE THREAD

**Issue by ecumene** [swatigetcoding0610/blue_bee#13]

**Comment by sverma06** [comment]
Created table for creating new product
`CREATE TABLE IF NOT EXISTS createProduct (
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        price REAL DEFAULT 0,
        quantity INTEGER DEFAULT 0,
        brand TEXT,
        color TEXT,
        material TEXT,
        weight REAL,
        age_range TEXT,
        dimensions REAL
    )`

**Comment by ecumene** [comment]
Hmm, the name could just be `products`. Everything else looks good!

**Comment by sverma06** [comment]
We already have one `products` table so renamed as `product`
