### ISSUE TITLE
Create a profile page

### ISSUE THREAD

**Issue by ecumene** [swatigetcoding0610/blue_bee#35]
Just a page that shows the user's username and other things.

**Comment by sverma06** [comment]
@ecumene If am removing navigation to home page when user clicks on login or signup, I am getting the username. But I am unable to navigate to home page as you asked me to remove it from backend also (we were getting errors). What is the alternative solution to this?

**Comment by sverma06** [comment]
<img width="1440" alt="Screen Shot 2022-12-13 at 10 41 18 AM" src="https://user-images.githubusercontent.com/114248907/207356198-624170d0-7801-4b8a-92b9-51518ef00aed.png">

**Comment by sverma06** [comment]
<img width="1440" alt="Screen Shot 2022-12-13 at 11 05 37 AM" src="https://user-images.githubusercontent.com/114248907/207361798-f07da481-91fe-498d-b836-86b113e53356.png">
