### ISSUE TITLE
GOAL: Create a Database Schema

### ISSUE THREAD

**Issue by ecumene** [swatigetcoding0610/blue_bee#7]
https://github.com/swatigetcoding0610/blue_bee/blob/35232aa517fc6f50a9a85763434c41bdbab6c2cf/backend/src/backend.js#L3

```js
const app = express()

const makeSchema = () => {
  // Setup SQLite DB
  // Create your schema
}

makeSchema();

...
app.use(express.static("public"))
...
```

**Comment by ecumene** [comment]
## Take a look at these when creating your schema

- [ ] Here’s a tutorial on create table in Sqlite: https://www.sqlitetutorial.net/sqlite-create-table/
- [ ] Here’s the Node-SQLite3 documentation: https://www.npmjs.com/package/sqlite3
- [ ] Here's my schema: https://github.com/radiks-llc/portal/blob/main/src/pages/api/auth/schema.ts

**Comment by sverma06** [comment]
@ecumene https://github.com/radiks-llc/portal/blob/main/src/pages/api/auth/schema.ts this link is not working.

**Comment by sverma06** [comment]
<img width="1392" alt="Screen Shot 2022-10-20 at 6 07 59 PM" src="https://user-images.githubusercontent.com/114248907/197053408-3aa9a2a2-1aa1-4f98-b845-2bf8a041e705.png">

**Comment by ecumene** [comment]
Sorry! I moved it 😆 https://github.com/radiks-llc/portal/blob/main/src/pages/login/api/auth/schema.ts

**Comment by sverma06** [comment]
I tried by referring your code and tutorial given above, however, I am getting error. 
Blogs and videos I referred are using separate file for sql. Can you please share any tutorial specific to this?
